
class mappers():
    
    def __init__(self, mapping_cat = "traffic"):
        if mapping_cat == "traffic":
            self.event_to_value = self.traffic_value_mapper()
            self.mapper_dict = {"traffic_cluster": self.get_traffic_cluster_mapping(),
                                "traffic_no_cluster": self.get_traffic_no_clustermapping()}
        if mapping_cat == "syntehetic":
            pass
    
    def get_traffic_cluster_mapping(self):
        mapper = {
            "sky is clear_0" : "sky is clear",
            "mist_0" : self.event_to_value["dense_fog"],
            "broken clouds_0" : "broken clouds",
            "light rain_0" : self.event_to_value["light_rain"],
            "broken clouds_1" : "broken clouds",
            "moderate rain_0" : self.event_to_value["rain"],
            "overcast clouds_0" : "overcast clouds",
            "overcast clouds_2" : "overcast clouds",
            "overcast clouds_1" : "overcast clouds",
            "scattered clouds_0" : "scattered clouds",
            "light intensity drizzle_0" : self.event_to_value["light_rain"],
            "haze_0" : self.event_to_value["light_fog"],
            "light rain_1" : self.event_to_value["light_rain"],
            "few clouds_1" : "few clouds",
            "light snow_0" : self.event_to_value["snow"],
            "scattered clouds_2" : "scattered clouds",
            "scattered clouds_1" : "scattered clouds",
            "fog_0" :  self.event_to_value["heavy_dense_fog"],
            "overcast clouds_3" : "overcast clouds",
            "mist_1" : self.event_to_value["dense_fog"],
            "mist_2" : self.event_to_value["dense_fog"],
            "broken clouds_2" : "broken clouds",
            "drizzle_0" : self.event_to_value["light_rain"],
            "proximity thunderstorm_0" : self.event_to_value["thunderstorm"],
            "few clouds_0" : "few clouds",
            "scattered clouds_3" : "scattered clouds",
            "heavy intensity rain_0" : self.event_to_value["heavy_rain"],
            "few clouds_2" : "few clouds",
            "heavy snow_0" : self.event_to_value["exstremly_heavy_snow"],
            "light snow_1" : self.event_to_value["snow"],
            "mist_3" : self.event_to_value["dense_fog"],
            "light snow_2" : self.event_to_value["snow"],
            "overcast clouds_4" : "overcast clouds",
            "light rain_2" : self.event_to_value["light_rain"],
            "snow_0" : self.event_to_value["snow"],
            "light snow_3" : self.event_to_value["snow"],
            "broken clouds_3" : "broken clouds",
            "moderate rain_1" : self.event_to_value["rain"],
            "mist_4" : self.event_to_value["dense_fog"],
            "haze_1" : self.event_to_value["light_fog"],
            "proximity shower rain_0" : self.event_to_value["heavy_rain"],
            "mist_5" : self.event_to_value["dense_fog"],
            "thunderstorm_0" : self.event_to_value["thunderstorm"],
            "light snow_4" : self.event_to_value["snow"],
            "proximity thunderstorm_1" : self.event_to_value["thunderstorm"],
            "heavy snow_1" : self.event_to_value["exstremly_heavy_snow"],
            "thunderstorm with heavy rain_0" : self.event_to_value["thunderstorm"],
            "broken clouds_4" : "broken clouds",
            "drizzle_1" : self.event_to_value["light_rain"],
            "heavy intensity drizzle_0" : self.event_to_value["light_rain"],
            "thunderstorm with light rain_0" : self.event_to_value["thunderstorm"],
            "fog_1" : self.event_to_value["heavy_dense_fog"],
            "haze_2" : self.event_to_value["light_fog"],
            "proximity thunderstorm with rain_0" : self.event_to_value["thunderstorm"],
            "heavy snow_3" : self.event_to_value["exstremly_heavy_snow"],
            "mist_6" : self.event_to_value["dense_fog"],
            "heavy snow_2" : self.event_to_value["exstremly_heavy_snow"],
            "thunderstorm with rain_0" : self.event_to_value["thunderstorm"],
            "haze_3" : self.event_to_value["light_fog"],
            "haze_7" : self.event_to_value["light_fog"],
            "proximity thunderstorm_2" : self.event_to_value["thunderstorm"],
            "heavy snow_4" : self.event_to_value["exstremly_heavy_snow"],
            "fog_2" : self.event_to_value["heavy_dense_fog"],
            "smoke_0" : "smoke",
            "very heavy rain_0" : self.event_to_value["exstremly_heavy_rain"],
            "heavy intensity rain_1" : self.event_to_value["rain"],
            "haze_4" : self.event_to_value["light_fog"],
            "heavy intensity rain_2" : self.event_to_value["rain"],
            "heavy snow_6" : self.event_to_value["exstremly_heavy_snow"],
            "thunderstorm with light drizzle_0" : self.event_to_value["thunderstorm"],
            "proximity thunderstorm with drizzle_0" : self.event_to_value["thunderstorm"],
            "light intensity shower rain_0" : self.event_to_value["light_rain"],
            "snow_1" : self.event_to_value["snow"],
            "haze_8" : self.event_to_value["light_fog"],
            "light shower snow_0" : self.event_to_value["snow"],
            "haze_5" : self.event_to_value["light_fog"],
            "moderate rain_2" : self.event_to_value["rain"],
            "heavy snow_5" : self.event_to_value["exstremly_heavy_snow"],
            "light rain and snow_0" : self.event_to_value["snow"],
            "shower drizzle_0" : self.event_to_value["light_rain"],
            "haze_6" : self.event_to_value["light_fog"],
            "scattered clouds_4" : "scattered clouds",
            "heavy intensity drizzle_1" : self.event_to_value["rain"],
            "mist_7" : self.event_to_value["dense_fog"],
            "SQUALLS_0" : "SQUALLS",
            "sleet_0" : "sleet",
            "thunderstorm with rain_1" : self.event_to_value["thunderstorm"],
            "freezing rain_0" : self.event_to_value["rain"],
            "few clouds_3" : "few clouds",
            "thunderstorm with drizzle_0" : self.event_to_value["thunderstorm"],
            "proximity thunderstorm with rain_1" : self.event_to_value["thunderstorm"],
            "proximity shower rain_1" : self.event_to_value["rain"],
            "heavy intensity rain_3" : self.event_to_value["heavy_rain"],
            "light intensity drizzle_1" : self.event_to_value["light_rain"], 
            "drizzle_2" : self.event_to_value["light_rain"],
            "proximity thunderstorm_3" : self.event_to_value["thunderstorm"],
            "sky is clear_1" : "sky is clear",
            "snow_2" : self.event_to_value["snow"],
            "shower snow_0" : self.event_to_value["snow"],
            "light rain_3" : self.event_to_value["light_rain"],
            "temp_6": "temp",
            "temp_3": "temp",
            "temp_5": "temp",
            "temp_2": "temp",
            "temp_4": "temp",
            "temp_0": "temp",
            "temp_7": "temp",
            "temp_1": "temp",
            "traffic_volume_2": self.event_to_value["traffic_volume_2"],
            "traffic_volume_0": self.event_to_value["traffic_volume_0"],
            "traffic_volume_1": self.event_to_value["traffic_volume_1"]
        }
        return mapper
    
    def get_traffic_no_clustermapping(self):
        mapper = {
            "Sky is Clear": "Sky is Clear",
            "sky is clear": "sky is clear",
            "mist":  self.event_to_value["dense_fog"],
            "broken clouds":"broken clouds",
            "light rain":self.event_to_value["light_rain"],
            "moderate rain":self.event_to_value["rain"],
            "overcast clouds": "overcast clouds",
            "scattered clouds":"scattered clouds",
            "light intensity drizzle": self.event_to_value["light_rain"],
            "haze": self.event_to_value["light_fog"],
            "few clouds":"few clouds",
            "light snow":self.event_to_value["snow"],
            "fog":self.event_to_value["heavy_dense_fog"],
            "drizzle":self.event_to_value["light_rain"],
            "proximity thunderstorm":self.event_to_value["thunderstorm"],
            "few clouds":"few clouds",
            "heavy snow":self.event_to_value["exstremly_heavy_snow"],
            "proximity shower rain":self.event_to_value["rain"],
            "thunderstorm":self.event_to_value["light_rain"],
            "proximity thunderstorm":self.event_to_value["thunderstorm"],
            "thunderstorm with heavy rain":self.event_to_value["light_rain"],
            "thunderstorm with light rain":self.event_to_value["light_rain"],
            "haze":self.event_to_value["light_fog"],
            "thunderstorm with rain":self.event_to_value["light_rain"],
            "very heavy rain":self.event_to_value["exstremly_heavy_rain"],
            "heavy intensity rain":self.event_to_value["heavy_rain"],
            "thunderstorm with light drizzle":self.event_to_value["light_rain"],
            "proximity thunderstorm with drizzle":self.event_to_value["light_rain"],
            "light intensity shower rain":self.event_to_value["light_rain"],
            "snow":self.event_to_value["snow"],
            "light shower snow":self.event_to_value["snow"],
            "moderate rain":self.event_to_value["rain"],
            "light rain and snow":self.event_to_value["snow"],
            "shower drizzle":self.event_to_value["light_rain"],
            "heavy intensity drizzle":self.event_to_value["rain"],
            "SQUALLS":"SQUALLS",
            "sleet":"sleet",
            "smoke":"smoke",
            "thunderstorm with rain":self.event_to_value["light_rain"],
            "freezing rain":self.event_to_value["rain"],
            "thunderstorm with drizzle":self.event_to_value["thunderstorm"],
            "proximity thunderstorm with rain":self.event_to_value["light_rain"],
            "shower snow": self.event_to_value["snow"],
            "temp_6":"temp",
            "temp_3":"temp",
            "temp_5":"temp",
            "temp_2":"temp",
            "temp_4":"temp",
            "temp_7":"temp",
            "temp_1":"temp",
            "temp_0":"temp",
            "traffic_volume_2": self.event_to_value["traffic_volume_2"],
            "traffic_volume_0": self.event_to_value["traffic_volume_0"],
            "traffic_volume_1": self.event_to_value["traffic_volume_1"]
        }
        return mapper

    def traffic_value_mapper(self):
        event_to_value = {
                "rain":[12.1,14,"rain"],
                "fog":[-7,1.1,"fog"],
                "mist":[7,"mist"],
                "haze":[14,"haze"],
                "snow":[-37.9,-65,"snow"],
                "light_fog":[1.4,"light_fog"],
                "dense_fog":[-8.3,"dense_fog"],
                "heavy_dense_fog":[-12.5,"heavy_dense_fog"],
                "light_rain":[-8.3,"light_rain"],
                "heavy_rain":[-3.4,"heavy_rain"],
                "exstremly_heavy_rain":[-13.5,"exstremly_heavy_rain"],
                "exstremly_heavy_snow":[-67.6,"exstremly_heavy_snow"],
                "hail":[6.8,"hail"],
                "thunderstorm":[-4.18,"thunderstorm"],
                "traffic_volume_2": [4131,7100],
                "traffic_volume_0": [269,1880],
                "traffic_volume_1": [1881,4130]
            }
        return event_to_value        